name = 'portfolio-page'
pages_build_output_dir = "./build"
compatibility_date = "2025-11-14"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "portfolio-page-production"

# Preview environment  
[env.preview]
name = "portfolio-page-preview"

# Preview environment variables
[env.preview.vars]
NODE_ENV = "staging"
VITE_API_URL = "https://api-staging.renekris.dev"

# Production environment variables
[env.production.vars]
NODE_ENV = "production"
VITE_API_URL = "https://api.renekris.dev"
