name = "renekris-dev-website"
pages_build_output_dir = "./build"
compatibility_date = "2025-09-15"

[env.production]
name = "renekris-dev-website-production"

[env.preview]
name = "renekris-dev-website-preview"

# Preview environment variables  
[env.preview.vars]
NODE_ENV = "staging"
REACT_APP_API_URL = "https://api-staging.renekris.dev"
